language: node_js
node_js:
 - "9.5"
script:
- nvm use 9.5
- yarn
- yarn prod:generator
- yarn generate
before_deploy:
- ls -lrt
deploy:
  skip_cleanup: true
  provider: firebase
  token: $FIREBASE_TOKEN
  message: "your message"
  project: tous-mes-droits
branches:
  only:
  - master