language: node_js
node_js:
 - "9.5"
script:
- echo "Deploy!!"
install:
- nvm use 9.5
- yarn global add firebase-tools
- yarn
after_success:
 - yarn prod:generator
 - yarn generate
 - firebase deploy -project tous-mes-droits -token $FIREBASE_TOKEN